### ISSUE TITLE
P1 | CAD | Simplified design

### ISSUE THREAD

**Issue by Zhongy1** [Zhongy1/LaserTag#12]
Assuming that the general cutout regions have been created, it is time to modify the frame and cutout regions using actual values. The goal is to create a design that can house all of the components necessary for a working prototype: microcontroller, IR LED, switch, boost converter, and battery. 
- Do not attempt to create detailed cutout regions, that task will done in a future issue. 
- Keep cutout regions rectangular. 
- You will have to print your design to actually show that everything fits.

Add more variables as needed. These will be filled in/modified overtime when measurements are collected. These variables go into Variables.scad.
Variables: (In millimeters)
- circBrdT = 0; //TBD
- circBrdSolderSpace = 3;
- ledBrdW = 10;
- ledBrdL = 10;
- ledHousingD = 5.4;
- ledHousingH = 0; //TBD
- microCtlrHousingW = 0; //TBD
- microCtlrHousingL = 0; //TBD
- microCtlrHousingH = 0; //TBD
- switchHousingW = 0; //TBD
- switchHousingL = 0; //TBD
- switchHousingH = 0; //TBD
- cnvrtrHousingW = 0; //TBD
- cnvrtrHousingL = 0; //TBD
- cnvrtrHousingH = 0; //TBD
- batteryHousingW = 0; //TBD
- batteryHousingL = 0; //TBD
- batteryHousingH = 0; //TBD

GunPieceBottom:
- create sub-modules for each cutout (i.e ctlrCutout, switchCutout, etc.). Doing this will make adding details easier in the future.
- call the sub-modules here; since the general cutout locations are established, all you might need to do is replace a few lines of code with ctlrCutout, switchCutout, etc.
- you will be using difference() here. Since the first item for difference is the thing you subtract from, use union() to gather pieces together first (i.e the frame of the gun)
- adjust size of gun overtime; use a variable to make changing the size easier if needed
- keep in mind that this is half of the gun, which means you will only be using half the housing heights. The other half of the height goes to GunPieceTop

GunPieceTop:
- If done right, you should be able to use the mirror of GunPieceBottom
- No need to worry about locking the top and bottom together, that can be done in another issue

**Comment by fdemp** [comment]
Microcontroller board + ESP8266 has a height of 17.4mm
