### ISSUE TITLE
P1 | Arduino | Send IR signals using ESP8266

### ISSUE THREAD

**Issue by Zhongy1** [Zhongy1/LaserTag#14]
It has been demonstrated that sending IR signals from the Arduino Uno works. Now it's time to do the same with the ESP8266. The library used on the Uno is different from the one that will be used for the ESP8266; a little bit of googling will give you an idea of what library to use. Do the following:

Create IR_ESP8266.ino in the Arduino folder; use this file to write the code to test sending/receiving signals.
- Create a function called emitHex which takes a hexadecimal string as input.
  - The only thing this function should do is cause IR LED to emit a signal
  - This function seems unnecessary, but in the future, this function will be modified to take an object/list of information and convert them into hex format to be emitted.
- A microcontroller should be able to both receive and send signals
- Use a transistor to control the LED, as this is what will be in the actual circuit
- An Arduino Uno can still be used as the receiver; to test at a distance

For the prototype, one microcontroller will control the receiving of signals and send information to the server. The other one will be inside the gun and it will control the sending of signals. Both microcontrollers will need to be connected to the server, but for this issue you don't need to worry about doing that. Once everything here works, assume that you will be copying code over to blaster_client and receiver_client.

**Comment by torashad99** [comment]
Added IR_ESP8266 file and created function prototype for emitHex function

**Comment by Zhongy1** [comment]
Use D1 as sender, D2 as switch, D3 as receiver
