### ISSUE TITLE
P1 | Circuitry | Solder components to microcontroller board

### ISSUE THREAD

**Issue by Zhongy1** [Zhongy1/LaserTag#19]
![IMG_0745](https://user-images.githubusercontent.com/34720343/67792845-d84c1e80-fa47-11e9-9a92-df85285f2221.jpg)

Do the following:
- Solder female header pins to regions marked in red
- Solder a 1K ohm resistor in region marked in green
- Solder a transistor into the region marked in blue, match the legs with the labels

All components should be inserted from the opposite side. Which means there should be no components on the copper side

**Comment by jpmossman** [comment]
Soldered the components to the board
![20191029_175844](https://user-images.githubusercontent.com/55605490/67815826-fdf01c80-fa75-11e9-91af-ea7baa49b86c.jpg)
![20191029_175840](https://user-images.githubusercontent.com/55605490/67815828-ffb9e000-fa75-11e9-9256-b45f13c9b011.jpg)
