### ISSUE TITLE
P2 | Arduino | Ammo Tracking Functionality

### ISSUE THREAD

**Issue by Zhongy1** [Zhongy1/LaserTag#42]
We had planned to implement ammo functionality for a while. This is the time to do that. For now we can hard code how much ammo is in a blaster. Maybe 8 is a good number. Each time the trigger is pulled, --ammo--++. There also needs a delay before the next shot can be made. Avoid using Arduino's delay function as that prevents other functionalities from running. To reload, hold down the trigger for 3 seconds. After three seconds, the blaster is reloaded and can output IR signals once again.

**Comment by awoo8** [comment]
This is also addressed in #52 and is completed in #54
