### ISSUE TITLE
P1 | NodeJS | String Decoder

### ISSUE THREAD

**Issue by Zhongy1** [Zhongy1/LaserTag#9]
Create a file called string-decoder.ts in the Server folder.
The contents of this file will be as follows

- class called StringDecoder
  - constructor (no parameters)
  - public static functions
    - toJson: converts string to a JSON object
  - private functions
    - any function that pay help you write toJson

Typescript will look something like this
```ts
public class StringDecoder {
    constructor() {}
    public static toJson(str: string) {
        return {};
    }
    private helper1() {}
    private helper2() {}
}
```

Be sure to follow these guidelines when you are creating your branch. This part is important very important. Post questions on this issue if you have any.
[Tutorials/Guidelines](https://docs.google.com/presentation/d/1K7jmuJYuWfzYJ1fsT3zaX4GJ7kZFKSX0ssIE4SxMXTo/edit?usp=sharing)

**Comment by FestiveAkp** [comment]
What is the format of the string? Will it be JSON itself, or will it just be a sentence that should be organized into a JSON structure? Is there an example of what an incoming string would look like?

**Comment by Zhongy1** [comment]
The format of the string is still to be determined. Currently, the plan is for the input to be like a sentence which would be converted into a JSON structure. This may change to sending a hexadecimal encoding instead if it turns out this method is easier/better to implement. For this issue, you are just creating the shell of the class. This means you can define empty functions that will be completed in a future issue.
